---
language: python
matrix:
  include:
    - python: 2.7
      dist: trusty
    - python: 3.3
      dist: trusty
    - python: 3.4
      dist: trusty
    - python: 3.5
      dist: trusty
    - python: 3.6
      dist: trusty
    - python: 3.7
      dist: xenial
    - python: nightly
      dist: xenial
    - python: pypy
      dist: trusty
  allow_failures:
    - python: nightly

before_install:
  - git submodule update --init --recursive
  - git clone --recursive git://github.com/maxmind/libmaxminddb
  - cd libmaxminddb
  - ./bootstrap
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..
  - pip install -e git+https://github.com/maxmind/MaxMind-DB-Reader-python#egg=maxminddb
install:
  - pip install -r requirements.txt
  - pip install requests_mock pylint coveralls yapf
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install ipaddr; fi"
script:
  - coverage run --source=geoip2 setup.py test
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then ./.travis-pylint.sh; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then ./.travis-yapf.sh; fi"
after_success:
  - coveralls
notifications:
  email:
    on_failure: always
    on_success: change
    recipients:
      - dev-ci@maxmind.com
  slack:
    rooms:
      secure: "FZLn7HZnM6GOtIU7+W6tY6zd2y0K4C1ZgIOAiGscWvJydn+Xr63GCT21EPPe9QCulQHz88CWALMD7ZrDdsh6nV0gx0IeE+wq4w7NZYjLokvxs+UMYwuwl57MMrqd7e4byZDC4BLvTQTCvpOHOd8dCHwDXmuBcuyE8zB+Wkndn0I=\n"
