language: python
python:
  - 2.6
  - 2.7
  - 3.1
  - 3.2
  - 3.3
script: nosetests
install:
  - pip install -r requirements.txt
  - pip install unittest2
notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always
