language: python
python:
  - 2.6
  - 2.7
  - 3.1
  - 3.2
  - 3.3
script: invoke test
install:
  - pip install -r requirements.txt
notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always
