language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - pypy

install:
  - pip install -r requirements.txt
  - pip install httpretty pylint coveralls
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2 ipaddr; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install ipaddr; fi

script:
  - coverage run --source=geoip2 setup.py test
  - if [[ $TRAVIS_PYTHON_VERSION != '3.3' ]]; then pylint geoip2; fi

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always
