language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
install:
  - pip install -r requirements.txt
  - pip install git+https://github.com/maxmind/HTTPretty.git
  - pip install pylint
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
script:
  - nosetests
  - if [[ $TRAVIS_PYTHON_VERSION != '3.3' ]]; then pylint geoip2; fi
notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always
